### ISSUE TITLE
Kickoff agenda

### ISSUE THREAD

**Issue by suprenant** [18F/navair-pa#1]
So we can organize an effective kickoff and develop a useful kickoff presentation, we need a kickoff agenda.

https://drive.google.com/open?id=1ngqA_oHvUUWoPmD4hOKgitCm2thKv7qb
https://drive.google.com/open?id=1tdVTKzcy9f_FFPQSyZDWkOlnvj8xa2-s

Acceptance criteria:
 - [ ] We have a kickoff agenda the team agrees will work for our needs

**Comment by suprenant** [comment]
Working this up here: https://docs.google.com/document/d/1WiOaVrFPhNDcp689snOycI1AuphOP5Jt4lFcHxXP7hg/edit#heading=h.15xbt3u4efud

**Comment by suprenant** [comment]
My preliminary draft is done. Pinging the team in Slack for feedback.

**Comment by suprenant** [comment]
From standup/Slack, Kathryn and TC will review today, and then I'll do another pass Monday so we can send a draft to the partner.

**Comment by suprenant** [comment]
From our pairing session, I am cleaning up the current agenda draft and will send to the partner shortly.

**Comment by suprenant** [comment]
Sent to partner. One of y'all want to accept (so we're each not accepting work we led ourselves)?

**Comment by tbaxter-18f** [comment]
+1

**Comment by suprenant** [comment]
Thanks for ultra-quick review @tbaxter-18f. I'm going to open this back up and put it in Done, which we can use for our review/report each week. Once we've reviewed/reported, we can do a batch to close up issues.
