### ISSUE TITLE
Initial README

### ISSUE THREAD

**Issue by suprenant** [18F/navair-pa#10]
README in repo with basic project information

**Comment by suprenant** [comment]
OK, I have a draft here. I want to add a bit more context here and call this done. Feel free to open PRs if you want to make updates: 

https://github.com/18F/navair-pa/blob/master/README.md

Once we've moved through kickoff, we can add more on the problem statement, our vision for the engagement, and other details here.

**Comment by suprenant** [comment]
I'm going to call this round done. There's more that I want to explore around our approach and steps we might take, but I'm going to shift to some other items for now. 

If someone can review this, that'd be helpful, and we can (and should) continue to add as we go along.

**Comment by tbaxter-18f** [comment]
Good first pass. +1
