### ISSUE TITLE
Documented initial findings and questions [timebox: EOD Monday]

### ISSUE THREAD

**Issue by suprenant** [18F/navair-pa#12]
From TC – what we're after:
 - From background materials
 - Some preliminary idea of how these data pieces may fit together
 - A starter list of questions we don’t have answers to yet

Some notes from what we've discussed to date:
 - Biggest challenge in manpower is determining what a workload is (from kickoff call)
 - Decrease variability (kickoff call)
 - The doc says “they don’t tie this to what’s causing people to stay or leave. “ which gives some indication they do have data, it’s just not tied together. (TC)
 - On that “ton of data” it says “Currently, reviewing and reconciling.” < who’s doing that, and what’s the output of that work look like? (TC)

Acceptance criteria:
 - [ ] We have our initial findings documented
 - [x] We have our initial questions documented
 - [x] We can verify that we have checked with our 18F team for input/feedback
 - [ ] We have time scheduled to discuss this with the partner

**Comment by suprenant** [comment]
@tbaxter-18f FYI, I groomed this a bit and retitled to reflect some additional context and direction. Let's chat if any of this doesn't seem right.

**Comment by suprenant** [comment]
From standup, let's timebox this to EOD Monday.

**Comment by tbaxter-18f** [comment]
WIP Doc: https://docs.google.com/document/d/1zGHtBJJURzePi3mDqMesMmgasTs2_ZVKFGfY10GQM4w/edit
I suspect that until we start seeing some of this data we're going to have a lot more questions than findings.

**Comment by suprenant** [comment]
Got it @tbaxter-18f. Can you please put this in the team folder so we can all easily access it? 

https://drive.google.com/drive/u/0/folders/1Zi8TiYQBV21oXyCYRQf2eXoKE0mXHEqQ

**Comment by suprenant** [comment]
@tbaxter-18f OK, I reviewed the questions doc – it was quite comprehensive. I added a few notes and suggestions for your review. 

Given our timebox is up, I suggest you review those, ping Kathryn for any last feedback/additions, and then we can reach out to the partner to set up a call to discuss, and we can call this done. How's that sound?
