### ISSUE TITLE
Preliminary problem and vision statements

### ISSUE THREAD

**Issue by suprenant** [18F/navair-pa#13]
....we should write these to make sure we're all aligned and then guide our work. 

Reference:
 - https://medium.com/eightshapes-llc/how-to-build-a-problem-statement-d1f21713720b
 - https://github.com/18F/strategy-internal/blob/master/path-analysis/approach.md#2-draft-a-problem-statement

Implementation steps:
 - [x] Do an [async problem statement exercise/worksheet via a Google Doc](https://docs.google.com/document/d/10HRPw8yM4g6jJ99s4XL97Z-2WEVSUnci0Hrg44zo5xc/edit#)
 - [x] Draft problem statement
 - [x] Draft preliminary vision
 - [ ] [stretch] Ping #strategy for feedback

Acceptance criteria:
 - [ ] We have a written draft of a problem statement that has been vetted by our 18F team
 - [ ] We have a written draft of a preliminary vision that has been vetted by our 18F team

**Comment by suprenant** [comment]
From standup, TC planning on picking this up next. I've been taking some notes on this, as well, so can help review/edit/pair.

**Comment by tbaxter-18f** [comment]
@suprenant do you want to just drop your notes somewhere I can pick them up?

**Comment by suprenant** [comment]
@tbaxter-18f my notes are a bit unwieldy and unstructured at this point. I'd suggest you start with a pass without them, and I can then review and add in bits from them where it seems useful. How does that sound?

**Comment by suprenant** [comment]
@tbaxter-18f FYI, I brought this into In Progress and linked your worksheet to the above for quick and clear reference.

**Comment by suprenant** [comment]
Getting back into this. FYI, I'm adding a preliminary vision as part of this work.

**Comment by suprenant** [comment]
I drafted some more of the problem and vision bullets and pinged TC for review.

**Comment by suprenant** [comment]
I opened a PR for the problem statement here: https://github.com/18F/navair-pa/pull/45

I am also noting that we will want to revisit these after kickoff to incorporate feedback and whatever else we learned/found.

**Comment by suprenant** [comment]
PR for vision statement: https://github.com/18F/navair-pa/pull/46

**Comment by suprenant** [comment]
I believe this issue is now done. Can one of y'all please accept?

**Comment by tbaxter-18f** [comment]
+1
