### ISSUE TITLE
NAVAIR system(s) access

### ISSUE THREAD

**Issue by suprenant** [18F/navair-pa#4]
So we can review data in the system, we need system access.

Possible systems:
 - Data challenge (John working on this)

Acceptance criteria:
- [ ] We have confirmed system access for Andrew
- [ ] We have confirmed system access for TC

Implementation steps:
- [x] SAAR (Andrew)
- [x] SAAR (TC)
- [x] Forms to/from GSA IT
 - [x]  Additional [training](https://iatraining.disa.mil/eta/disa_cac2018/launchPage.htm ) (TC)
 - [x]  Additional training (Andrew)

**Comment by suprenant** [comment]
I filled out my form and sent to Michael for signature

**Comment by suprenant** [comment]
Kathryn routing me and TC's forms through GSA security and then back to Navy.

**Comment by suprenant** [comment]
These are in GSA security. Kathryn pinged GSA security, will monitor.

**Comment by suprenant** [comment]
From Slack, a discussion of CAC/PIV cards we may need for access: https://gsa-tts.slack.com/archives/CBJLRSU5D/p1532704315000067

**Comment by MKathrynC** [comment]
sent to partners.

**Comment by suprenant** [comment]
Super, thank you @MKathrynC. I reopened this issue so we can track it until it's done.

**Comment by suprenant** [comment]
From standup, this is in NAVAIR's court. We'll keep following up with them on this.

**Comment by suprenant** [comment]
From email, we need to do additional training: https://iatraining.disa.mil/eta/disa_cac2018/launchPage.htm

**Comment by suprenant** [comment]
OK, I finished the training and sent the certificate to the cybersecurity team.

**Comment by suprenant** [comment]
From standup, TC resent his SAAR this morning, so we're waiting back on NAVAIR.

**Comment by suprenant** [comment]
From Kathryn's request, I updated the security training date and submitted to our partner contacts.

**Comment by suprenant** [comment]
From Slack, Kathryn has been following up on this. More to come.

**Comment by suprenant** [comment]
From standup, let's look at this and get what we can to GSA security to see if we can get access: https://handbook.18f.gov/top-secret/

**Comment by suprenant** [comment]
From standup, TC working to draft a justification for the form.

**Comment by suprenant** [comment]
TC's submitted his paperwork to 18F/GSA, waiting to hear back.

**Comment by tbaxter-18f** [comment]
Following https://handbook.18f.gov/top-secret/, all of my paperwork is now submitted to my supervisor and are expected to be signed and passed on to HR -- and then on to GSA security -- hopefully by EOD today or possibly Monday.

**Comment by suprenant** [comment]
Picking this up myself now...

**Comment by suprenant** [comment]
OK, I'm done with the forms excepting a few questions I had for TC on one of them. I'll pick this back up on Monday but expect to be able to get signatures from Michael and ship to the next step then.

**Comment by suprenant** [comment]
Update: I've filled out my forms and sent to my supervisor for signature. Once I get these back, I'll forward to whoever is next in the chain (I believe GSA security).

**Comment by suprenant** [comment]
Update – my forms have now been signed, and I sent them to TTS Talent to process and forward to GSA Security.

**Comment by suprenant** [comment]
From standup, TC's pending supervisory PD should help expedite things. We haven't heard from Talent on this yet. We both sent our forms yesterday so will give them another day and then ping.

**Comment by suprenant** [comment]
From standup, TC shares that his application is in process, and Kathryn will check in with Talent and Security to see if mine is moving forward, check in on which step of the process will allow us to tell Navy we have submitted, and share again our feelings of urgency with this.

**Comment by suprenant** [comment]
@MKathrynC anything to share today re: the system access question?

**Comment by suprenant** [comment]
As an update, Stephanie Fonteneaux just emailed me and Michael asking for some more information for the interim clearance. So mine appears to be moving forward.

**Comment by suprenant** [comment]
As an update, Michael has sent back the required information to Stephanie.

**Comment by suprenant** [comment]
From Stephanie: _Thank you, Andrew for returning the completed forms.  The next step is for the classifier to finish the PD--that usually takes anywhere from a couple of days up to a week.  Once that happens, I will notify you and your supervisor that the package has been assembled and routed through HR to Security for processing._

**Comment by suprenant** [comment]
From standup, it's been about a week since TC heard from Jenn M., so he will follow up with her.

**Comment by tbaxter-18f** [comment]
From Jennifer Moran: Waiting for our HR team to review and put the package together for security ... will try to push them to complete this this week

**Comment by suprenant** [comment]
From planning, this is moving forward, TC working on eQIP form. Unfortunately, it seems too late for this engagement. Kathryn can also check with April.

**Comment by suprenant** [comment]
For our tracking purpose, I'm marking this done and filing under wont. If we have happy surprises in the next few days, let's keep in touch :)
