### ISSUE TITLE
Textual analysis of exit interview survey questions

### ISSUE THREAD

**Issue by tbaxter-18f** [18F/navair-pa#52]
What we're after:

Notes:
 - What themes do we see
 - We also want to develop a sense of what was tried previously

Acceptance criteria:
 - [ ] We have a written summary of our learnings from this

**Comment by suprenant** [comment]
Waiting on free-text data

**Comment by tbaxter-18f** [comment]
With these survey questions coming back into the HR pipeline, I would encourage NAVAIR to seek responses whenever possiible and do a textual analysis on those response -- similar to the PD analysis done in this engagement in order to look for patterns that may not be uncovered by the structured data questions.

Right now, the older data has too few responses for any meaningful analysis.
