### ISSUE TITLE
Visual artifact supporting attrition hypothesis [Amy]

### ISSUE THREAD

**Issue by suprenant** [18F/navair-pa#54]
Charting a Course:
https://docs.google.com/drawings/d/1RPRzLBCbhLpfgtquoV0NivIejrEJOm5XRM-VQ4lAzZo/edit?ts=5b76db14&pli=1

Implementation steps:
 - [ ]  Identify who can help us
 - [ ]  Identify and articulate need
 - [ ] Make it so

**Comment by suprenant** [comment]
As discussed from @tbaxter-18f. Pinged Kathryn in Slack to determine budget we may have available for design help.

**Comment by suprenant** [comment]
From Slack today, looks like we probably have up to ten hours for this and other support, so a half or full day of design time could be feasible. I suggest we start to identify who may be able to help and also keep our ears open for other subject matter or thinking we develop that could similarly benefit from visual representation. 

Edit: we do have #design-lab

**Comment by tbaxter-18f** [comment]
I think either #design-lab, or reach out to Liz.

**Comment by tbaxter-18f** [comment]
Per Liz, this would go through design-lab so: https://github.com/18F/design-lab/issues/20

**Comment by suprenant** [comment]
We chatted with Aviva just now, who feels like she can have something for us next week. She'll be busier at the beginning of September on another engagement, so we should make the most use of her time for the next two weeks.

**Comment by suprenant** [comment]
From planning, TC to ping Aviva to sync on where we are regarding this hypothesis this week.

**Comment by suprenant** [comment]
From TC in Slack on this: _Amy Ashida is taking over our visualization. She's been briefed, and still expects to have a draft mid-week and probably final version by EOW_

**Comment by suprenant** [comment]
From standup, waiting on Amy for a revision.

**Comment by tbaxter-18f** [comment]
Looks done to me! https://github.com/18F/design-lab/issues/20#issuecomment-417767829

**Comment by tbaxter-18f** [comment]
Final files can be found at https://docs.google.com/presentation/d/1EC-uvN10kwZY1ywIjWUhj6WzHmQ3B37psai83R1V-IM/edit#slide=id.g40945e821e_0_0
