### ISSUE TITLE
Analysis of data challenge data [timebox: Wednesday EOD]

### ISSUE THREAD

**Issue by suprenant** [18F/navair-pa#55]
What we're after:

Notes:
 - 15-20 files (e.g. workload planning, structured exit interview data)
 - What themes do we see
 - We also want to develop a sense of what was tried previously

Acceptance criteria:
 - [ ] We have a written summary of our learnings from this

**Comment by tbaxter-18f** [comment]
I have received a link to the Data Challenge materials in AMRDEC.

**Comment by suprenant** [comment]
From Slack/standup, we still could use more context here.
