### ISSUE TITLE
Kickoff date and approved travel auth

### ISSUE THREAD

**Issue by suprenant** [18F/navair-pa#7]
Acceptance criteria:
 - [x] We have a confirmed kickoff date and times
 - [x] We have travel approvals (Andrew)
 - [x] We have travel approvals (Kathryn)
 - [ ] We have travel approvals (TC)

**Comment by suprenant** [comment]
Pending kickoff dates.

**Comment by suprenant** [comment]
@MKathrynC anything to report on setting the kickoff date/time?

**Comment by MKathrynC** [comment]
*Thursday, August 9th from 9:30 - 3:00*

Details:
Kick-off meeting for the 18F engagement on NAVAIR FRCSE Human Capital analysis.

Will discuss project scope, deliverable expectations, discuss the project plan, data needs, and next steps.

Kevin will provide background on enterprise Human Capital data systems and analysis to-date. John will provide additional insight into FRC specific systems/processes with support from FRC team.

Regards,
Kevin

**Comment by suprenant** [comment]
From standup, TC will look at his travel possibilities and send to Kathryn, and we can figure out the rest of our arrangements from there.

**Comment by suprenant** [comment]
@MKathrynC can you share where we are re: travel auth? All of our arrangements are booked, so we will just need the auth to move through.

**Comment by suprenant** [comment]
As an update, I just got confirmation that Ethan approved my travel auth. Let us know, team, if you don't get yours.
