### ISSUE TITLE
Synthesis of analysis work (prior to Week 6)

### ISSUE THREAD

**Issue by suprenant** [18F/navair-pa#75]
TC analysis doc: https://docs.google.com/document/d/1B6f4B8M8L9lSb2K1dzHrW_uPiOes1vrBpSBWcw9w0Jw/edit#

**Comment by suprenant** [comment]
@tbaxter-18f FYI, I've marked the report as dependent on this synthesis work. Think you can make this happen this week so we can fold into the WIP report by Monday?

**Comment by tbaxter-18f** [comment]
I need to!

**Comment by suprenant** [comment]
❤️ 

LMK if you want to pair or if we can do anything to make room on your plate!

**Comment by suprenant** [comment]
From TC, sounds like this is done – TC, LMK if that's not right.
