### ISSUE TITLE
Preliminary NAVAIR data set

### ISSUE THREAD

**Issue by suprenant** [18F/navair-pa#9]
**Key items**
 - [x] Exit interview data (Diane is working on, but the data is old - 2015)
 - [x] Data challenge data (shared with us via AMRDEC)
 - [x] Position description skills data (structured data on employee skills)

**Other**
 - [x] Demand supply cycle data
 - [ ] Attrition data
 - [ ] Various retention factors, programs and incentives (to start getting a sense of both the efficacy and cost of those ASAP)
 - [ ] Other data schema that may be useful

**Comment by suprenant** [comment]
@MKathrynC from standup (and Slack), TC and I are feeling blocked because we don't know the shape of the data, so it's hard for us to finding a starting point for our work. 

In our call earlier this week, NAVAIR said they could send us the data schema and possibly starter data. Can you please follow up on this? If you don't have capacity, let us know, and TC and I can follow up.

**Comment by suprenant** [comment]
From email, Kathryn pinged.

**Comment by suprenant** [comment]
Kathryn to ping a bit later today and will say that this is critical to our moving forward.

**Comment by suprenant** [comment]
Received from John:
 - COMFRC NDMS Solution (NAVAIR IT infrastructure) deck

**Comment by suprenant** [comment]
From email this morning, TC requested this:
* Exit interview data
* Attrition data
* Demand supply cycle data
* HR data -- I understand there is a lot to sift through here, but any starting point would be helpful
* We understand there is a similar, parallel data mining effort going on within NAVAIR. Would it be possible to share what they’ve found so far?
* Similarly, we understand there have been efforts with other entities (Deloitte, American Air) -- can we see the output of those efforts?

**Comment by suprenant** [comment]
@tbaxter-18f FYI, I reorganized the various items we're looking for and prioritized them in this issue description. Can you please take a look and edit or note if anything seems to be off/missing?

**Comment by suprenant** [comment]
From standup today – we will ask about this and call this out as a risk in our partner meeting today. I will plan to ask about it tomorrow to escalate as needed, and, as TC pointed out, Kathryn and he have already asked, so it'll be my turn :)

**Comment by tbaxter-18f** [comment]
Made some edits. Nice cleanup. Thanks Andrew.

**Comment by suprenant** [comment]
From email, TC pinged partner re: videoconferencing so we can walk through these materials.

**Comment by suprenant** [comment]
From standup:
 - Diane is working on the data challenge data and should have that by early week of 8/20
 - Kevin and his team are scrubbing the exit interview data and expect it approximately EOD Friday

**Comment by suprenant** [comment]
I reworked this card description to more accurately represent what we're looking for here.

**Comment by tbaxter-18f** [comment]
Data challenge materials have been shared in AMRDEC

**Comment by suprenant** [comment]
Confirming I received the data challenge files from AMRDEC as well.

**Comment by tbaxter-18f** [comment]
Exit interview data only goes up to 2015, and then has a gap until just now. Need to confirm with partner if there is still sufficient utility to pursue.
